remote_theme: jekyll/minima

author:
    name: Violet Ballard
    email: "violet@rvgames.company"

minima:
  skin: dark

  social_links: 
    - { platform: github, user_url: "https://github.com/violetballard/disrupter" }
    - { platform: twitter, user_url: "https://twitter.com/idofinternet" }