remote_theme: jekyll/minima

author:
    name: Violet Ballard
    email: "violet@rvgames.company"

header_pages:
   - README.md
   - rules/core/main.md
   - rules/core/panic.md
   - rules/core/vehicles.md
   - rules/core/indirect_fire.md
   - game_modes/main.md
   - platoons/main.md
   - platoons/starter.md
   - rules/optional/size_of_force.md
   - platoons/platoon_card.md
   - equipment/main.md
   - equipment/armor.md
   - equipment/bots.md
   - equipment/weapons.md
   - equipment/vehicles.md
   - LICENSE.md
   - TODO.md

minima:
  skin: dark

  social_links: 
    - { platform: github, user_url: "https://github.com/violetballard/disrupter" }
    - { platform: twitter, user_url: "https://twitter.com/idofinternet" }